services:
  mc-server:
    # Build image from local Dockerfile
    build: .
    # Allow typing commands in the server console
    tty: true
    stdin_open: true
    # Restart container automatically unless manually stopped
    restart: unless-stopped
    ports:
      # Map host port 8888 to Minecraft's default port 25565
      - "8888:25565"
    env_file:
      - .env
    volumes:
      # Mounts the "local_data" volume into /app (persistent storage)
      - local_data:/app/

# Defines the named volume "local_data"
volumes:
  local_data: